-- Bảng PHONGHOC
CREATE TABLE PHONGHOC (
    ID_PHONGHOC NVARCHAR(5) NOT NULL PRIMARY KEY,
    TENPHONGHOC NVARCHAR(50) NOT NULL,
    MAPHONG CHAR(10) NOT NULL,
    MOTA TEXT NULL,
    TRANGTHAI BIT DEFAULT 1,
    ID_USER NVARCHAR(5) NULL,
    CONSTRAINT FK_PHONGHOC_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);

-- Bảng LOAITAINGUYEN
CREATE TABLE LOAITAINGUYEN (
    ID_LOAITN NVARCHAR(5) NOT NULL PRIMARY KEY,
    TENLOAITN NVARCHAR(50) NOT NULL,
    TRANGTHAI BIT DEFAULT 1
);

-- Bảng ROLES
CREATE TABLE ROLES (
    ID_ROLE NVARCHAR(5) NOT NULL PRIMARY KEY,
    TENROLE NVARCHAR(50) NOT NULL,
    TRANGTHAI BIT DEFAULT 1
);

-- Bảng USERS
CREATE TABLE USERS (
    ID_USER NVARCHAR(5) NOT NULL PRIMARY KEY,
    TENUSER NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL,
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    TRANGTHAI BIT DEFAULT 1,
    ID_ROLE NVARCHAR(5) NOT NULL,
    ANHDAIDIEN TEXT NULL,
    GIOITINH BIT NULL,
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);

-- Bảng PHONGHOCTHAMGIA
CREATE TABLE PHONGHOCTHAMGIA (
    ID_PHONGHOC NVARCHAR(5) NOT NULL,
    ID_USER NVARCHAR(5) NOT NULL,
    VAITRO TINYINT NOT NULL,
    PRIMARY KEY (ID_PHONGHOC, ID_USER),
    CONSTRAINT FK_PHONGHOCTHAMGIA_PH FOREIGN KEY (ID_PHONGHOC) REFERENCES PHONGHOC (ID_PHONGHOC)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
    CONSTRAINT FK_PHONGHOCTHAMGIA_US FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);

-- Bảng TAINGUYENHOCTAP
CREATE TABLE TAINGUYENHOCTAP (
    ID_TAINGUYEN NVARCHAR(5) NOT NULL PRIMARY KEY,
    TENTAINGUYEN NVARCHAR(50) NOT NULL,
    URL_TAINGUYEN TEXT NOT NULL,
    MOTA TEXT NULL,
    TRANGTHAI BIT DEFAULT 1,
    ID_LOAITN NVARCHAR(5) NOT NULL,
    ID_PHONGHOC NVARCHAR(5) NOT NULL,
    ID_USER NVARCHAR(5) NOT NULL,
    THOIHAN DATETIME NULL,
    NGAYDANG DATETIME NULL,
    CONSTRAINT FK_TAINGUYEN_LOAITN FOREIGN KEY (ID_LOAITN) REFERENCES LOAITAINGUYEN (ID_LOAITN)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
    CONSTRAINT FK_TAINGUYEN_PHONGHOC FOREIGN KEY (ID_PHONGHOC) REFERENCES PHONGHOC (ID_PHONGHOC)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
    CONSTRAINT FK_TAINGUYEN_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);

-- Bảng KETQUAHOCTAP
CREATE TABLE KETQUAHOCTAP (
    ID_USER NVARCHAR(5) NOT NULL,
    ID_TAINGUYEN NVARCHAR(5) NOT NULL,
    KETQUA FLOAT DEFAULT 0,
    TIENTRINH BIT DEFAULT 0,
    PRIMARY KEY (ID_USER, ID_TAINGUYEN),
    CONSTRAINT FK_KETQUA_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
    CONSTRAINT FK_KETQUA_TAINGUYEN FOREIGN KEY (ID_TAINGUYEN) REFERENCES TAINGUYENHOCTAP (ID_TAINGUYEN)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);
