CREATE DATABASE QLHOCTRUCTUYEN
USE QLHOCTRUCTUYEN

CREATE TABLE PHONGHOC (
	ID_PHONGHOC NVARCHAR(5) NOT NULL,
	TENPHONGHOC NVARCHAR(50) NOT NULL,
	MAPHONG CHAR(10) NOT NULL,
	MOTA TEXT NULL,
	TRANGTHAI BIT DEFAULT 1,

	CONSTRAINT PK_PHONGHOC PRIMARY KEY (ID_PHONGHOC)
);

CREATE TABLE LOAITAINGUYEN (
	ID_LOAITN NVARCHAR(5) NOT NULL,
	TENLOAITN NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,

	CONSTRAINT PK_LOAITAINGUYEN PRIMARY KEY (ID_LOAITN)
);

CREATE TABLE ROLES (
	ID_ROLE NVARCHAR(5) NOT NULL,
	TENROLE NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,

	CONSTRAINT PK_ROLE PRIMARY KEY (ID_ROLE)
);

CREATE TABLE USERS (
	ID_USER NVARCHAR(5) NOT NULL,
	TENUSER NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
	PASSWORD_HASH NVARCHAR(255) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,

	ID_ROLE NVARCHAR(5) NOT NULL,

	CONSTRAINT PK_USERS PRIMARY KEY (ID_USER),
	CONSTRAINT FK_USERS FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,

);

CREATE TABLE PHONGHOCTHAMGIA (
	ID_PHONGHOC NVARCHAR(5) NOT NULL,
	ID_USER NVARCHAR(5) NOT NULL,
	VAITRO TINYINT NOT NULL,

	CONSTRAINT PK_PHONGHOCTHAMGIA PRIMARY KEY (ID_PHONGHOC, ID_USER),
	CONSTRAINT FK_PHONGHOCTHAMGIA_PHONGHOC  FOREIGN KEY (ID_PHONGHOC) REFERENCES PHONGHOC (ID_PHONGHOC)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	CONSTRAINT FK_PHONGHOCTHAMGIA_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE TAINGUYENHOCTAP (
	ID_TAINGUYEN NVARCHAR(5) NOT NULL,
	TENTAINGUYEN NVARCHAR(50) NOT NULL,
	URL_TAINGUYEN TEXT NOT NULL,
	MOTA TEXT NULL,
	TRANGTHAI BIT DEFAULT 1,
	ID_USER NVARCHAR(5) NOT NULL,

	CONSTRAINT PK_TAINGUYENHOCTAP PRIMARY KEY (ID_TAINGUYEN),
	CONSTRAINT FK_TANGUYENTHOCTAP FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE KETQUAHOCTAP (
	ID_USER NVARCHAR(5) NOT NULL,
	ID_TAINGUYEN NVARCHAR(5) NOT NULL,

	KETQUA FLOAT DEFAULT 0,
	TIENTRINH BIT DEFAULT 0,

	CONSTRAINT PK_KETQUAHOCTAP PRIMARY KEY (ID_USER, ID_TAINGUYEN),
	CONSTRAINT FK_KETQUAHOCTAP_USER  FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	CONSTRAINT FK_KETQUAHOCTAP_TAINGUYEN  FOREIGN KEY (ID_TAINGUYEN) REFERENCES TAINGUYENHOCTAP (ID_TAINGUYEN)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

ALTER TABLE TAINGUYENHOCTAP
ADD ID_LOAITN NVARCHAR(5) NOT NULL;

ALTER TABLE TAINGUYENHOCTAP
ADD CONSTRAINT FK_TAINGUYENHOCTAP_LOAITN FOREIGN KEY (ID_LOAITN) 
    REFERENCES LOAITAINGUYEN (ID_LOAITN) 
    ON DELETE NO ACTION 
    ON UPDATE CASCADE;

ALTER TABLE TAINGUYENHOCTAP
ADD ID_PHONGHOC NVARCHAR(5) NOT NULL;

ALTER TABLE TAINGUYENHOCTAP
ADD CONSTRAINT FK_TAINGUYENHOCTAP_PHONGHOC FOREIGN KEY (ID_PHONGHOC) 
    REFERENCES PHONGHOC (ID_PHONGHOC) 
    ON DELETE NO ACTION 
    ON UPDATE CASCADE;
