CREATE DATABASE QLHOCTRUCTUYEN
USE QLHOCTRUCTUYEN

CREATE TABLE PHONGHOC (
	ID_PHONGHOC NVARCHAR(5) NOT NULL,
	TENPHONGHOC NVARCHAR(50) NOT NULL,
	MAPHONG CHAR(10) NOT NULL,
	MOTA TEXT NULL,
	TRANGTHAI BIT DEFAULT 1,

	CONSTRAINT PK_PHONGHOC PRIMARY KEY (ID_PHONGHOC)
);

CREATE TABLE LOAITAINGUYEN (
	ID_LOAITN NVARCHAR(5) NOT NULL,
	TENLOAITN NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,

	CONSTRAINT PK_LOAITAINGUYEN PRIMARY KEY (ID_LOAITN)
);

CREATE TABLE ROLES (
	ID_ROLE NVARCHAR(5) NOT NULL,
	TENROLE NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,

	CONSTRAINT PK_ROLE PRIMARY KEY (ID_ROLE)
);

CREATE TABLE USERS (
	ID_USER NVARCHAR(5) NOT NULL,
	TENUSER NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
	PASSWORD_HASH NVARCHAR(255) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,

	ID_ROLE NVARCHAR(5) NOT NULL,

	CONSTRAINT PK_USERS PRIMARY KEY (ID_USER),
	CONSTRAINT FK_USERS FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,

);

CREATE TABLE PHONGHOCTHAMGIA (
	ID_PHONGHOC NVARCHAR(5) NOT NULL,
	ID_USER NVARCHAR(5) NOT NULL,
	VAITRO TINYINT NOT NULL,

	CONSTRAINT PK_PHONGHOCTHAMGIA PRIMARY KEY (ID_PHONGHOC, ID_USER),
	CONSTRAINT FK_PHONGHOCTHAMGIA_PHONGHOC  FOREIGN KEY (ID_PHONGHOC) REFERENCES PHONGHOC (ID_PHONGHOC)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	CONSTRAINT FK_PHONGHOCTHAMGIA_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
);

CREATE TABLE TAINGUYENHOCTAP (
	ID_TAINGUYEN NVARCHAR(5) NOT NULL,
	TENTAINGUYEN NVARCHAR(50) NOT NULL,
	URL_TAINGUYEN TEXT NOT NULL,
	MOTA TEXT NULL,
	TRANGTHAI BIT DEFAULT 1,
	CONSTRAINT PK_TAINGUYENHOCTAP PRIMARY KEY (ID_TAINGUYEN)
);

CREATE TABLE KETQUAHOCTAP (
	ID_USER NVARCHAR(5) NOT NULL,
	ID_TAINGUYEN NVARCHAR(5) NOT NULL,

	KETQUA FLOAT DEFAULT 0,
	TIENTRINH BIT DEFAULT 0,

	CONSTRAINT PK_KETQUAHOCTAP PRIMARY KEY (ID_USER, ID_TAINGUYEN),
	CONSTRAINT FK_KETQUAHOCTAP_USER  FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	CONSTRAINT FK_KETQUAHOCTAP_TAINGUYEN  FOREIGN KEY (ID_TAINGUYEN) REFERENCES TAINGUYENHOCTAP (ID_TAINGUYEN)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);

ALTER TABLE TAINGUYENHOCTAP
ADD ID_LOAITN NVARCHAR(5) NOT NULL;

ALTER TABLE TAINGUYENHOCTAP
ADD CONSTRAINT FK_TAINGUYENHOCTAP_LOAITN FOREIGN KEY (ID_LOAITN) 
    REFERENCES LOAITAINGUYEN (ID_LOAITN) 
    ON DELETE NO ACTION 
    ON UPDATE CASCADE;

ALTER TABLE TAINGUYENHOCTAP
ADD ID_PHONGHOC NVARCHAR(5) NOT NULL;

ALTER TABLE TAINGUYENHOCTAP
ADD CONSTRAINT FK_TAINGUYENHOCTAP_PHONGHOC FOREIGN KEY (ID_PHONGHOC) 
    REFERENCES PHONGHOC (ID_PHONGHOC) 
    ON DELETE NO ACTION 
    ON UPDATE CASCADE;

ALTER TABLE TAINGUYENHOCTAP
ADD	ID_USER NVARCHAR(5) NOT NULL

ALTER TABLE TAINGUYENHOCTAP
ADD THOIHAN DATETIME NULL
NGAYDANG DATETIME NULL

DELETE FROM TAINGUYENHOCTAP
	

ALTER TABLE TAINGUYENHOCTAP
ADD CONSTRAINT FK_TAINGUYENTHOCTAP_USERS FOREIGN KEY (ID_USER) 
REFERENCES USERS (ID_USER)
ON DELETE NO ACTION
ON UPDATE CASCADE
	



INSERT INTO PHONGHOC (ID_PHONGHOC, TENPHONGHOC, MAPHONG, MOTA, TRANGTHAI)
VALUES 
('P001', 'Phòng học A1', 'A1-001', 'Phòng học lý thuyết', 1),
('P002', 'Phòng học B1', 'B1-002', 'Phòng học thực hành', 1),
('P003', 'Phòng học C1', 'C1-003', 'Phòng học đa năng', 1);

INSERT INTO LOAITAINGUYEN (ID_LOAITN, TENLOAITN, TRANGTHAI)
VALUES 
('L001', 'Tài liệu tham khảo', 1),
('L002', 'Bài giảng', 1),
('L003', 'Video học tập', 1);

INSERT INTO TAINGUYENHOCTAP (ID_TAINGUYEN, TENTAINGUYEN, URL_TAINGUYEN, MOTA, TRANGTHAI, ID_USER, ID_LOAITN, ID_PHONGHOC, THOIHAN, NGAYDANG)
VALUES
('T001', 'Tài liệu Toán 1', 'http://example.com/math1', 'Tài liệu học toán lớp 1', 1, 'U0', 'L001', 'P001', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T002', 'Video Sinh học', 'http://example.com/bio', 'Video học sinh học lớp 6', 1, 'U0', 'L003', 'P002', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T003', 'Bài giảng Vật lý', 'http://example.com/physics', 'Bài giảng vật lý lớp 10', 1, 'U0', 'L002', 'P003', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T004', 'Tài liệu Hóa học', 'http://example.com/chemistry', 'Tài liệu học hóa lớp 12', 1, 'U0', 'L001', 'P002', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T005', 'Video Lịch sử', 'http://example.com/history', 'Video học lịch sử lớp 9', 1, 'U0', 'L003', 'P001', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T006', 'Bài giảng Địa lý', 'http://example.com/geography', 'Bài giảng địa lý lớp 8', 1, 'U1', 'L002', 'P003', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T007', 'Tài liệu Ngữ văn', 'http://example.com/literature', 'Tài liệu ngữ văn lớp 11', 1, 'U0', 'L001', 'P003', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T008', 'Video Tiếng Anh', 'http://example.com/english', 'Video học tiếng Anh giao tiếp', 1, 'U1', 'L003', 'P002', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T009', 'Bài giảng Tin học', 'http://example.com/it', 'Bài giảng tin học cơ bản', 1, 'U1', 'L001', 'P001', DATEADD(MONTH, 1, GETDATE()), GETDATE()),
('T010', 'Tài liệu Thể dục', 'http://example.com/pe', 'Tài liệu hướng dẫn thể dục', 1, 'U1', 'L001', 'P003', DATEADD(MONTH, 1, GETDATE()), GETDATE());



SELECT * FROM TAINGUYENHOCTAP

ALTER TABLE TAINGUYENHOCTAP
DROP CONSTRAINT FK_TAINGUYENTHOCTAP;

